project:
  type: website
lang: de

website:
  title: "![Health for Future Dresden](/images/logo_wide.png){width='20%' fig-align='center'} Health for Future Dresden"
  # title: "Health for Future Dresden"
  # title: "![Health for Future Dresden](/images/logo_wide.png){width='40%' fig-align='center'}"
  cookie-consent: true
  page-footer: "[Impressum](/impressum.qmd) - [Datenschutzerkl채rung](/datenschutzerklaerung.qmd)"
  favicon: images/logo.png
  twitter-card: true
  image: images/logo.png
  open-graph: true
  site-url: https://dresden.healthforfuture.de/
  navbar:
    left:
      - text: "Start"
        file: index.qmd
      - news.qmd
      - mitmachen.qmd
#      - text: "Vortr채ge"
#        file: vortraege.qmd
      - text: 'Arbeitsgruppen'
        menu:
          - text: "Koordination"
            file: arbeitsgruppen/koordination.qmd
          - text: "Zero Emission Hospital"
            file: arbeitsgruppen/zero_emission_hospital.qmd
          - text: "Initiative Nachhaltige Praxis"
            file: arbeitsgruppen/nachhaltige_praxis.qmd
          - text: "Divestment"
            file: arbeitsgruppen/divestment.qmd
          - text: "Politikergespr채che"
            file: arbeitsgruppen/politikergespraeche.qmd
          - text: "Pressearbeit"
            file: arbeitsgruppen/pressearbeit.qmd
          - text: "Ern채hrung"
            file: arbeitsgruppen/ernaehrung.qmd
          - text: "Lehre"
            file: arbeitsgruppen/lehre.qmd
          - text: "Hygienemuseum"
            file: arbeitsgruppen/hygienemuseum.qmd
          - text: "Hitzschutz"
            file: arbeitsgruppen/hitzeschutz.qmd
      - links.qmd
    right:
      # - icon: facebook
      #   href: https://www.facebook.com/healthforfuturedresden
      - icon: instagram
        href: https://www.instagram.com/healthforfuturedresden/
#  margin-header: naechste_termine.qmd
filters:
   - lightbox
# lightbox: auto

format:
  html:
    theme: cosmo
    css: styles.css
    grid:
      margin-width: 400px
    # email-obfuscation: javascript

